version: '3.9'

services:
  travelagencyrust:
    image: travelagencyrust
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/travel_agency
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#    ports:
#      - '5432:5432'
    volumes:
      - ./database/create_postgres.sql:/docker-entrypoint-initdb.d/create_postgres.sql
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: {}
