apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            -  containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db-name

---

apiVersion: v1
kind: Service
metadata: 
  name:  postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Secret
metadata: 
  name:  postgres-secret
  namespace: travelagency
stringData:
  postgres-user: postgres
  postgres-password: postgres
  postgres-db-name: travel_agency
