apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelagency
  labels:
    app: travelagency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelagency
  template:
    metadata:
      labels:
        app: travelagency
    spec:
      containers:
        - name: travelagency
          image: travelagency
          imagePullPolicy: Never
          env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@travelagency-postgres.travelagency.svc.cluster.local/travel_agency
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: travelagency
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: travelagency
