# consolidated manifest (built with kustomize)
apiVersion: v1
kind: Namespace
metadata:
  name: travelagency
---
apiVersion: v1
kind: Service
metadata:
  name: travelagency-postgres
  namespace: travelagency
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: travelagency-travelagency
  namespace: travelagency
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: travelagency
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: travelagency-postgres
  namespace: travelagency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres-user
              name: postgres-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: postgres-secret
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: postgres-db-name
              name: postgres-secret
        image: postgres
        name: postgres
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: travelagency
  name: travelagency-travelagency
  namespace: travelagency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelagency
  template:
    metadata:
      labels:
        app: travelagency
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@travelagency-postgres.travelagency.svc.cluster.local/travel_agency
        image: travelagency
        imagePullPolicy: Never
        name: travelagency
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Secret
metadata: 
  name:  postgres-secret
  namespace: travelagency
stringData:
  postgres-user: postgres
  postgres-password: postgres
  postgres-db-name: travel_agency
