-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 10:36:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema travel_agency
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `travel_agency` ;

-- -----------------------------------------------------
-- Schema travel_agency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travel_agency` DEFAULT CHARACTER SET utf8 ;
USE `travel_agency` ;

-- -----------------------------------------------------
-- Table `travel_agency`.`Accommodations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`Accommodations` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`Accommodations` (
  `id` INT NOT NULL,
  `hotel` VARCHAR(120) NOT NULL,
  `guests` INT NOT NULL,
  `checkin` DATETIME NOT NULL,
  `checkout` DATETIME NULL,
  `room` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_agency`.`TravelInsurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`TravelInsurance` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`TravelInsurance` (
  `id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `purposeOfTrip` VARCHAR(80) NOT NULL,
  `luggage` DECIMAL(10,2) NULL,
  `medical_cover` DECIMAL(10,2) NULL,
  `price_total` DECIMAL(10,2) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_agency`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`Client` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`Client` (
  `id` INT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `address` VARCHAR(200) NULL,
  `occupation` VARCHAR(120) NULL,
  `birth_date` DATETIME NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_agency`.`TravelPackages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`TravelPackages` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`TravelPackages` (
  `id` INT NOT NULL,
  `description` VARCHAR(120) NOT NULL,
  `client_id` INT NOT NULL,
  `country` VARCHAR(80) NOT NULL,
  `city` VARCHAR(80) NOT NULL,
  `accommodation_id` INT NULL,
  `insurance_id` INT NULL,
  `price_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tour_accommodation_idx` (`accommodation_id` ASC),
  INDEX `fk_tour_insurance_idx` (`insurance_id` ASC),
  INDEX `fk_tour_client_idx` (`client_id` ASC),
  CONSTRAINT `fk_tour_accommodation`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `travel_agency`.`Accommodations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_insurance`
    FOREIGN KEY (`insurance_id`)
    REFERENCES `travel_agency`.`TravelInsurance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `travel_agency`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_agency`.`Itinerary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`Itinerary` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`Itinerary` (
  `id` INT NOT NULL,
  `destination` VARCHAR(120) NOT NULL,
  `departure` DATETIME NOT NULL,
  `arrival` DATETIME NULL,
  `transport_kind` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_agency`.`EventTickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`EventTickets` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`EventTickets` (
  `id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `description` VARCHAR(80) NOT NULL,
  `location` VARCHAR(80) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_agency`.`GuidedTours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`GuidedTours` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`GuidedTours` (
  `id` INT NOT NULL,
  `description` VARCHAR(120) NOT NULL,
  `date` DATETIME NOT NULL,
  `participants` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
